apiVersion: v1
kind: Namespace
metadata:
  name: deel-assessment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deel-assessment
  namespace: deel-assessment
spec:
  selector:
    matchLabels:
      app: deel-assessment
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: deel-assessment
    spec:
      containers:
      - name: deel-assessment
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 100Mi
             cpu: 0.25

        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: deel-assessment-svc
  namespace: deel-assessment

spec:

  selector:
    app: deel-assessment

  ports:
    - name: http
      port: 80
      nodePort: 30000

  type: NodePort
